version: "3"
services:
  db:
    restart: always
    image: "postgres"
    container_name: "my_postgres"
    networks:
      - postgres
    environment:
      - POSTGRES_USER=jdev
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydb
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: johngicharu10@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - ./pgadmin:/root/.pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: always
networks:
  postgres:
    driver: bridge
# docker inspect  {postgressContainerID} | grep IPAddress
